sensor:
  - platform: wifi_signal
    name: "WIFI Signal Strength"
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: "dBm"
    update_interval: 60s
    id: wifi_signal_strength
    icon: "mdi:wifi-strength-3"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "WIFI SSID"
      entity_category: diagnostic
      id: wifi_ssid
      icon: "mdi:wifi"
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      id: ip_address
      icon: "mdi:ip"

  - platform: template
    name: "Software Version"
    entity_category: diagnostic
    id: software_version
    icon: "mdi:information-variant"
    lambda: |-
      return std::string("${sw_version}");

  - platform: uptime
    name: "System Uptime"
    format:
      separator: " "
    id: system_uptime
    icon: "mdi:clock-start"
